// Generated by RevLang
// Struct: Player

var base = Module.findBaseAddress("game.exe");

var health = Memory.readU32(base.add(0x1A4));
var mana = Memory.readU32(base.add(0x1A8));
var name = Memory.readUtf8String(base.add(0x1B0));
var level = Memory.readU32(base.add(0x1B4));

// Print values
console.log("health: ", health);
console.log("mana: ", mana);
console.log("name: ", name);
console.log("level: ", level);
